# Server settings 
server:
  port: 80
  address: 0.0.0.0
  max-http-header-size: 8192
# 24 hours
  session:
    timeout: 86400
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    basedir: /
    maxThreads: 10
    minSpareThreads: 3
    accesslog:
      directory: /home/log/server_log
      pattern: combined
      enabled: true
# DATASOURCE
#jdbc:
#  driverLocation: D:\\repo\\mysql\\mysql-connector-java\\5.1.38\\mysql-connector-java-5.1.38.jar
#  driverClass: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf-8
#  username: root
#  password: 123456
 
# SPRING PROFILES 
spring:
  aop:
    # Add @EnableAspectJAutoProxy.
    auto: true
    # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
    proxy-target-class: false

  devtools:
    restart:
      enabled: true
      exclude: target/**,static/**,log/**,.idea/**
      additional-path: src/main/java


  cache:
    jcache:
      config: ehcache.xml
#      config: hibernate-ehcache.xml
#    cache-names: ehcache
#      ehcache:
#        config: ehcache.xml
  mvc:
    throw-exception-if-no-handler-found: false


  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding:
      enabled: true
      force: true
    # HTTP message conversion
    # Preferred JSON mapper to use for HTTP message conversion. Set to "gson" to force the use of Gson when both it and Jackson are on the classpath.
    converters:
      preferred-json-mapper: gson
    multipart:
      max-file-size: 200Mb
      max-request-size: 400Mb

  thymeleaf:
    cache: false
    #cache: true
    encoding: UTF-8
    enabled: true
    excluded-view-names: jsp/
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #username: root
    #password: 123456
    username: rootsa
    password: Moses12345
    #备份
    usedatabase: spring
    backupdir: "d:/backup"
    aabackupcron: "0 0/1 * * * ? *"
    backupcron: "0 0 1 1/1 * ? *"

    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size:  5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1;
#    validation-query: SELECT 1 FROM DUAL;
    test-on-borrow: false
    test-while-idle: true
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    #proxyFilters: wall2
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.wall.selectWhereAlwayTrueCheck=false;druid.wall.conditionAndAlwayTrueAllow=true

    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true







#  data:
#    solr:
#      host: http://127.0.0.1:8983/solr
#      repositories:
#        enabled: true

  jpa:
    database: MYSQL
    database-platform: MYSQL
    generate-ddl: true
    hibernate:
      # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
      ddl-auto: update
      # ddl-auto: create
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.show_sql: true
      #hibernate.format_sql: true
      #hibernate.show_sql: false
      hibernate.format_sql: false

      # Allows Hibernate to generate SQL optimized for a particular DBMS
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.max_fetch_depth: 3
      hibernate.enable_lazy_load_no_trans: true
      hibernate.jdbc.fetch_size: 50

      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: d:/lucene
      hibernate.search.jmx_enabled: true
      hibernate.search.generate_statistics: true
      hibernate.search.lucene_version: LUCENE_5_3_1

#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: true
#      hibernate.cache.provider_class: org.hibernate.cache.EhCacheProvider
#      hibernate.cache.provider_configuration_file_resource_path: hibernate-ehcache.xml
#      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory



# MyBatis
#mybatis:
#  typeAliasesPackage: com.modou.**.domain
#  mapperLocations: classpath:/com/modou/**/mapper/*.xml
#  configLocation: classpath:/mybatis-config.xml
 
#
#  hornetq:
#    embedded:
#      cluster-password: # LOGGING
#logging:
#  level:
#    com.ibatis: DEBUG
#    org.hibernate.SQL: DEBUG





security:
  user:
    name: root
    password: Moses12345
management:
  security:
    roles: ADMIN
    enabled: true
  #Do not Modify,this path is configured in spring security check
  context-path: /admins


mail:
  smtps1:
    host: smtp.mailgun.org
    auth: true
    username: postmaster@sandbox6e03981472514c8ea3c3100c85097cd2.mailgun.org
    password: 0fcfd57dbe16ee111296e37f9d5c681e
    port: 25
  smtps:
    host: smtp.qiye.163.com
    auth: true
    username: liuxuan@labthink.com
    password: Moses0319

    port: 25


#JMX
#
#management:
#
#  port: 8081
#  address: 127.0.0.1
#  security:
#    enabled: false
#  context-path: /manage


#系统配置
SprKi:
  avatar:
    storePath: ./static/uploaded/avatar/
    accessUrlPath: /uploaded/avatar/
  domain: 127.0.0.1
  druid:
    username: root
    password: Moses12345
  faqlist:
    # 100 200 400
    count: 200
  lucene:
    chinese: true
    init: false
  upload:
    domain: 192.168.7.202
    #建议不要修改，否则无法访问到
    savepathroot: ./static/
    savepathchild: /uploaded/
    #访问文件的地址
    accesspath: /uploaded/
    #备份位置
    backupattachpath: d:/backup/attachments/
    #受限文件存储位置
    restrictedpath: d:/restrictedFiles
    #视频上传位置
    videoPath: d:/restrictedFiles
  editor:
    acl: ROLE_USER
  filemanage:
    basepath: f:/sss
  ticket:
    enablemail: true
    mailto: liuxuan@liuxuan.net
    editRole: ROLE_FAQ
  department:
    role:
      prefix: ROLE_DEPT
      autocreate: true